/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    'service-brochures': ServiceBrochure;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'service-brochures': ServiceBrochuresSelect<false> | ServiceBrochuresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Utilisé dans l'URL de l'article. Laissez vide pour le générer depuis le titre.
   */
  slug: string;
  publishedAt?: string | null;
  author?: string | null;
  categories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-brochures".
 */
export interface ServiceBrochure {
  id: number;
  title: string;
  category: 'traiteur' | 'mariages' | 'chef-a-domicile' | 'receptions';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'service-brochures';
        value: number | ServiceBrochure;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  author?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  heroImage?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-brochures_select".
 */
export interface ServiceBrochuresSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroImage?: (number | null) | Media;
  aboutImage?: (number | null) | Media;
  valuesPrimaryImage?: (number | null) | Media;
  valuesSecondaryImage?: (number | null) | Media;
  valuesBridgeImage?: (number | null) | Media;
  hero?: {
    locationLine?: string | null;
    titleWords?: string | null;
    titleAccent?: string | null;
    subtitle?: string | null;
    tagline?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
  };
  marquee?: {
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  serviceImages?: {
    traiteur?: (number | null) | Media;
    mariages?: (number | null) | Media;
    chefADomicile?: (number | null) | Media;
    receptions?: (number | null) | Media;
  };
  servicesText?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    traiteur?: {
      title?: string | null;
      sub?: string | null;
      desc?: string | null;
    };
    mariages?: {
      title?: string | null;
      sub?: string | null;
      desc?: string | null;
    };
    chefADomicile?: {
      title?: string | null;
      sub?: string | null;
      desc?: string | null;
    };
    receptions?: {
      title?: string | null;
      sub?: string | null;
      desc?: string | null;
    };
  };
  galleryText?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
  };
  gallery?:
    | {
        image?: (number | null) | Media;
        title?: string | null;
        note?: string | null;
        alt?: string | null;
        position?: string | null;
        id?: string | null;
      }[]
    | null;
  pavillonImages?: {
    main?: (number | null) | Media;
    portrait?: (number | null) | Media;
    table?: (number | null) | Media;
    stripOne?: (number | null) | Media;
    stripTwo?: (number | null) | Media;
    stripThree?: (number | null) | Media;
  };
  pavillonText?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    badgeKicker?: string | null;
    badgeQuote?: string | null;
    points?:
      | {
          label: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    linkUrl?: string | null;
    linkLabel?: string | null;
    linkNote?: string | null;
    stripKicker?: string | null;
    stripTitle?: string | null;
  };
  values?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    signatureKicker?: string | null;
    signatureQuote?: string | null;
    bands?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    items?:
      | {
          value: number;
          suffix?: string | null;
          label: string;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    featuredNote?: string | null;
    footerNote?: string | null;
    ctaLabel?: string | null;
    /**
     * Le premier avis de la liste est mis en avant en haut de la section.
     */
    items?:
      | {
          quote: string;
          author: string;
          occasion?: string | null;
          source?: ('site' | 'tripadvisor') | null;
          id?: string | null;
        }[]
      | null;
  };
  clients?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    /**
     * Laissez vide pour garder les logos par défaut du site.
     */
    logos?:
      | {
          image?: (number | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  serviceAreasText?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  contact?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    responseNote?: string | null;
    briefItems?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  finalCta?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    ctaLabel?: string | null;
  };
  footer?: {
    tagline?: string | null;
  };
  about?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    firstParagraph?: string | null;
    secondParagraph?: string | null;
    quote?: string | null;
    quoteAuthor?: string | null;
    ctaLabel?: string | null;
  };
  pricing?: {
    eyebrow?: string | null;
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    intro?: string | null;
    footerNote?: string | null;
    ctaLabel?: string | null;
    /**
     * Créez une ligne par saison tarifaire. Si une année est marquée comme affichée, le site utilisera celle-ci.
     */
    years?:
      | {
          label: string;
          isActive?: boolean | null;
          categories?:
            | {
                label: string;
                summaryLabel?: string | null;
                offers?:
                  | {
                      name: string;
                      price: string;
                      unit?: string | null;
                      sub?: string | null;
                      tone?: string | null;
                      detail?: string | null;
                      features?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      highlight?: boolean | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  aboutImage?: T;
  valuesPrimaryImage?: T;
  valuesSecondaryImage?: T;
  valuesBridgeImage?: T;
  hero?:
    | T
    | {
        locationLine?: T;
        titleWords?: T;
        titleAccent?: T;
        subtitle?: T;
        tagline?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
      };
  marquee?:
    | T
    | {
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  serviceImages?:
    | T
    | {
        traiteur?: T;
        mariages?: T;
        chefADomicile?: T;
        receptions?: T;
      };
  servicesText?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        traiteur?:
          | T
          | {
              title?: T;
              sub?: T;
              desc?: T;
            };
        mariages?:
          | T
          | {
              title?: T;
              sub?: T;
              desc?: T;
            };
        chefADomicile?:
          | T
          | {
              title?: T;
              sub?: T;
              desc?: T;
            };
        receptions?:
          | T
          | {
              title?: T;
              sub?: T;
              desc?: T;
            };
      };
  galleryText?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        title?: T;
        note?: T;
        alt?: T;
        position?: T;
        id?: T;
      };
  pavillonImages?:
    | T
    | {
        main?: T;
        portrait?: T;
        table?: T;
        stripOne?: T;
        stripTwo?: T;
        stripThree?: T;
      };
  pavillonText?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        badgeKicker?: T;
        badgeQuote?: T;
        points?:
          | T
          | {
              label?: T;
              text?: T;
              id?: T;
            };
        linkUrl?: T;
        linkLabel?: T;
        linkNote?: T;
        stripKicker?: T;
        stripTitle?: T;
      };
  values?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        signatureKicker?: T;
        signatureQuote?: T;
        bands?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        items?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              detail?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        featuredNote?: T;
        footerNote?: T;
        ctaLabel?: T;
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              occasion?: T;
              source?: T;
              id?: T;
            };
      };
  clients?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        logos?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  serviceAreasText?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        responseNote?: T;
        briefItems?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        ctaLabel?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        firstParagraph?: T;
        secondParagraph?: T;
        quote?: T;
        quoteAuthor?: T;
        ctaLabel?: T;
      };
  pricing?:
    | T
    | {
        eyebrow?: T;
        titleLineOne?: T;
        titleLineTwo?: T;
        intro?: T;
        footerNote?: T;
        ctaLabel?: T;
        years?:
          | T
          | {
              label?: T;
              isActive?: T;
              categories?:
                | T
                | {
                    label?: T;
                    summaryLabel?: T;
                    offers?:
                      | T
                      | {
                          name?: T;
                          price?: T;
                          unit?: T;
                          sub?: T;
                          tone?: T;
                          detail?: T;
                          features?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          highlight?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}